# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('articleid', models.IntegerField(db_column='articleId', primary_key=True, serialize=False)),
                ('articlename', models.CharField(db_column='articleName', max_length=100)),
                ('articleauther', models.CharField(blank=True, db_column='articleAuther', max_length=50, null=True)),
                ('articlepic', models.CharField(blank=True, db_column='articlePic', max_length=200, null=True)),
                ('articlecolumm', models.IntegerField(db_column='articleColumm')),
                ('articletime', models.DateField(db_column='articleTime')),
            ],
            options={
                'db_table': 'articles',
            },
        ),
        migrations.CreateModel(
            name='Columns',
            fields=[
                ('colid', models.AutoField(db_column='colId', primary_key=True, serialize=False)),
                ('colname', models.CharField(blank=True, db_column='colName', max_length=50, null=True)),
            ],
            options={
                'db_table': 'columns',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.AutoField(db_column='userId', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='userName', max_length=50)),
                ('userpassword', models.CharField(db_column='userPassword', max_length=60)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
